### ISSUE TITLE
No "More events" button

### ISSUE THREAD

**Issue by elmaxe** [datasektionen/bawang#30]
There exists a "More news" button, but no "More events" button. If there are more than 4 upcoming events, a button should appear saying that there are more events, that is not currently the case which is confusing.

Should be fixed in [src/components/Frontpage/index.js](https://github.com/datasektionen/bawang/blob/master/src/components/Frontpage/index.js)

![image](https://user-images.githubusercontent.com/33149910/143939667-e93cc621-708a-409c-893a-89bdb716fc33.png)

Discovered thanks to @triggerdude33

**Comment by kokoaono** [comment]
can I have a go at this please.
