### ISSUE TITLE
Långa namn overflowar i nyheter

### ISSUE THREAD

**Issue by elmaxe** [datasektionen/bawang#41]
![image](https://user-images.githubusercontent.com/33149910/191237876-e4bbac3b-6b4f-4bd6-9ec1-87e9a2481778.png)

Fixas lätt i css

**Comment by Grunler** [comment]
Långa ord i nyheterna overflowar också, t.ex. långa url:er.

**Comment by abbliseng** [comment]
https://github.com/datasektionen/bawang/pull/52
