### ISSUE TITLE
"Edit this page on github"

### ISSUE THREAD

**Issue by LudwikJaniuk** [datasektionen/bawang#6]
Vi borde ha en knapp som tar dig till att göra en pull request i github på bawang-content på varje sida!

**Comment by addem1234** [comment]
Fanns förut men togs bort pga mörkläggning. Är ju ez att lägga till igen
men känns som man vill ha en annan lösning?

**Comment by bullfest** [comment]
Något som typ vore en rätt trevlig lösning på mörkläggning i framtiden är att ha inloggning på alla system, inkl. bawang (då man i detta fall kan se denna sida).
Sen på login kan man pinga stön och fråga om en person som försöker logga in är nØllan.
Det skulle också göra att vi inte behöver sänka massa information och göra den otillgänglig för våra medlemmar varje år.

**Comment by LudwikJaniuk** [comment]
Ja, mörkläggningsprocessen återkommer ju varje år så det är ganska korkat att vi inte har det systematiserat. Men för att lägga tillbaka contribute-knappen just nu, @addem1234 vilken commit togs den bort i?

**Comment by addem1234** [comment]
Den har inte hängt med i den här Git historiken, kanske finns i gloo-bawang nån stans. Tvek om det är värt att leta efter med tanke på att det bara är en `<a href>GitHub</a>` på valfri plats i `src/Default/index.js`.

**Comment by LudwikJaniuk** [comment]
yeah, inte värt
