### ISSUE TITLE
Make all navigation buttons change color on hover

### ISSUE THREAD

**Issue by Benjaneb** [datasektionen/bawang#72]
When you hover over buttons they need to react in some way, like changing to a darker tone and/or changing size, which clearly signals that they're clickable and makes it just feel nicer. This is missing on all the nav bar buttons, the side bar buttons on subpages, all cerise buttons on the main page, and also all regular text links.

**Comment by hunxjunedo** [comment]
@Benjaneb please assign this issue to me, I'm willing to work
